In [50]:
!pip install streamlit

Requirement already satisfied: streamlit in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (1.58.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (6.2.1)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (7.1.4)
Requirement already satisfied: click<9,>=7.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (2.2.6)
Requirement already satisfied: packaging>=20 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (12.2.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (7.35.0)
Requirement already satisfied: pyarrow>=7.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (2.34.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (1.2.1)
Requirement already satisfied: uvicorn>=0.30.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: colorama in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from anyio>=4.0.0->streamlit) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: h11>=0.8 in c:\users\moham\miniconda3\envs\proj_2.1_venv\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)

In [51]:
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from datetime import datetime

Data inspection

In [52]:
df=pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\project_4.1\Date\samplesuperstore.csv")

In [53]:
df.shape

(10194, 21)

In [54]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [55]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [56]:
print(df[["Sales","Profit","Quantity","Discount"]].describe())

              Sales        Profit      Quantity      Discount
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854     28.673417      3.791838      0.155385
std      619.906839    232.465115      2.228317      0.206249
min        0.444000  -6599.978000      1.000000      0.000000
25%       17.220000      1.760800      2.000000      0.000000
50%       53.910000      8.690000      3.000000      0.200000
75%      209.500000     29.297925      5.000000      0.200000
max    22638.480000   8399.976000     14.000000      0.800000

In [57]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

data cleaning

In [58]:
print("duplicate rows:",df.duplicated().sum())
dupes=df[df.duplicated(subset=["Order ID"],keep=False)]
print(dupes.shape)
dupes.head()

duplicate rows: 0
(7601, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
5,6,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
6,7,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796

In [59]:
df["Order Date"]=pd.to_datetime(df["Order Date"])
df["Ship Date"]=pd.to_datetime(df["Ship Date"])
df["Shipping_days"]=(df["Ship Date"] - df["Order Date"]).dt.days

In [60]:
print(df.groupby("Region")["Shipping_days"].mean().round(1))

Region
Central    4.1
East       3.9
South      4.0
West       3.9
Name: Shipping_days, dtype: float64

In [61]:
df["Profit Margin"]= df["Profit"] / df["Sales"]*100
df["Profit Margin"] = df["Profit Margin"].round(2)
print(df.groupby("Sub-Category")["Profit Margin"].mean().round(2))

Sub-Category
Accessories    21.82
Appliances    -14.90
Art            25.22
Binders       -19.46
Bookcases     -13.51
Chairs          4.71
Copiers        32.04
Envelopes      42.35
Fasteners      30.63
Furnishings    13.98
Labels         42.46
Machines       -6.89
Paper          42.50
Phones         12.25
Storage         9.08
Supplies       11.44
Tables        -14.02
Name: Profit Margin, dtype: float64

In [62]:
df["Order Year"]=df["Order Date"].dt.year

In [63]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping_days', 'Profit Margin', 'Order Year'],
      dtype='object')

In [64]:
df.rename(
    columns={
        "Row ID": "row_id",
        "Order ID": "order_id",
        "Order Date": "order_date",
        "Ship Date": "ship_date",
        "Ship Mode": "ship_mode",
        "Customer ID": "customer_id",
        "Customer Name": "customer_name",
        "Segment": "segment",
        "Country/Region": "country_region",
        "City": "city",
        "State/Province": "state_province",
        "Postal Code": "postal_code",
        "Region": "region",
        "Product ID": "product_id",
        "Category": "category",
        "Sub-Category": "sub_category",
        "Product Name": "product_name",
        "Sales": "sales",
        "Quantity": "quantity",
        "Discount": "discount",
        "Profit": "profit",
        "Shipping Time": "shipping_time",
        "Shipping_days": "shipping_days",
        "Profit Margin": "profit_margin",
        "Order Year": "order_year"
    },
    inplace=True
)

In [66]:
df.to_csv(r"C:\Users\moham\OneDrive\Desktop\project_4.1\Output\superstore_cleaned.csv", index=False)